apiVersion: v1
kind: Service
metadata:
  name: lemo-service-recommender-item
  namespace: lemo-dev
  labels:
    app: item-service
    version: v1
spec:
  type: ClusterIP
  ports:
  - port: 8085
    targetPort: 8085
    protocol: TCP
    name: grpc
  selector:
    app: item-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-service
  namespace: lemo-dev
  labels:
    app: item-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: item-service
      version: v1
  template:
    metadata:
      labels:
        app: item-service
        version: v1
    spec:
      containers:
      - name: item-service
        image: registry.cn-beijing.aliyuncs.com/lemo/recommender:latest
        imagePullPolicy: Always
        command: ["python", "services/item/main.py"]
        ports:
        - containerPort: 8085
          name: grpc
          protocol: TCP
        envFrom:
        - configMapRef:
            name: lemo-services-config
        - secretRef:
            name: lemo-services-secret
        env:
        - name: GRPC_PORT
          value: "8085"
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
      imagePullSecrets:
      - name: aliyun-docker-registry

